% This test file was generated by Copilot. Validate the generated output before use.
classdef MyAddTest < matlab.unittest.TestCase
    methods(Test)
        function testAdditionWithPositiveNumbers(testCase)
            in1 = 5;
            in2 = 10;
            expectedOutput = 15;

            actualOutput = my_add(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testAdditionWithNegativeNumbers(testCase)
            in1 = -3;
            in2 = -7;
            expectedOutput = -10;

            actualOutput = my_add(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testAdditionWithMixedNumbers(testCase)
            in1 = 4;
            in2 = -2;
            expectedOutput = 2;

            actualOutput = my_add(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end
    end
end