% This test file was generated by Copilot. Validate the generated output before use.
classdef MyCalculateTest < matlab.unittest.TestCase
    methods(Test)
        function testAddition(testCase)
            in1 = 5;
            in2 = 3;
            expected = 8;

            actual = my_calculate(in1, in2, "add");

            testCase.verifyEqual(actual, expected);
        end

        function testSubtraction(testCase)
            in1 = 5;
            in2 = 3;
            expected = 2;

            actual = my_calculate(in1, in2, "subtract");

            testCase.verifyEqual(actual, expected);
        end

        function testMultiplication(testCase)
            in1 = 5;
            in2 = 3;
            expected = 15;

            actual = my_calculate(in1, in2, "multiply");

            testCase.verifyEqual(actual, expected);
        end

        function testDivision(testCase)
            in1 = 6;
            in2 = 3;
            expected = 2;

            actual = my_calculate(in1, in2, "divide");

            testCase.verifyEqual(actual, expected);
        end

        function testInvalidOperation(testCase)
            in1 = 5;
            in2 = 3;
            operation = "invalid";

            testCase.verifyError(@() my_calculate(in1, in2, operation), "MATLAB:InvalidOp");
        end
    end
end