% This test file was generated by Copilot. Validate the generated output before use.
classdef MyDivideTest < matlab.unittest.TestCase
    methods(Test)
        function testWithPositiveNumbers(testCase)
            in1 = 10;
            in2 = 2;
            expectedOutput = 5;

            actualOutput = my_divide(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testWithNegativeNumbers(testCase)
            in1 = -10;
            in2 = -2;
            expectedOutput = 5;

            actualOutput = my_divide(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testWithMixedNumbers(testCase)
            in1 = -10;
            in2 = 2;
            expectedOutput = -5;

            actualOutput = my_divide(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testDivisionByOne(testCase)
            in1 = 10;
            in2 = 1;
            expectedOutput = 10;

            actualOutput = my_divide(in1, in2);

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testDivisionByZero(testCase)
            in1 = 10;
            in2 = 0;

            testCase.verifyError(@() my_divide(in1, in2), "MATLAB:DivideByZero");
        end
    end
end