% This test file was generated by Copilot. Validate the generated output before use.
classdef MyMultiplyTest < matlab.unittest.TestCase
    methods(Test)
        function testWithPositiveNumbers(testCase)
            in1 = 3;
            in2 = 4;
            expectedProduct = 12;

            actualProduct = my_multiply(in1, in2);

            testCase.verifyEqual(actualProduct, expectedProduct);
        end

        function testWithNegativeNumbers(testCase)
            in1 = -3;
            in2 = -4;
            expectedProduct = 12;

            actualProduct = my_multiply(in1, in2);

            testCase.verifyEqual(actualProduct, expectedProduct);
        end

        function testWithMixedNumbers(testCase)
            in1 = -3;
            in2 = 4;
            expectedProduct = -12;

            actualProduct = my_multiply(in1, in2);

            testCase.verifyEqual(actualProduct, expectedProduct);
        end

        function testWithZero(testCase)
            in1 = 0;
            in2 = 5;
            expectedProduct = 0;

            actualProduct = my_multiply(in1, in2);

            testCase.verifyEqual(actualProduct, expectedProduct);
        end
    end
end