% This test file was generated by Copilot. Validate the generated output before use.
classdef MySubtractTest < matlab.unittest.TestCase
    methods(Test)
        function testWithPositiveNumbers(testCase)
            in1 = 5;
            in2 = 3;
            expectedDifference = 2;

            actualDifference = my_subtract(in1, in2);

            testCase.verifyEqual(actualDifference, expectedDifference);
        end

        function testWithNegativeNumbers(testCase)
            in1 = -5;
            in2 = -3;
            expectedDifference = -2;

            actualDifference = my_subtract(in1, in2);

            testCase.verifyEqual(actualDifference, expectedDifference);
        end

        function testWithMixedNumbers(testCase)
            in1 = 3;
            in2 = -2;
            expectedDifference = 5;

            actualDifference = my_subtract(in1, in2);

            testCase.verifyEqual(actualDifference, expectedDifference);
        end

        function testWithZero(testCase)
            in1 = 0;
            in2 = 5;
            expectedDifference = -5;

            actualDifference = my_subtract(in1, in2);

            testCase.verifyEqual(actualDifference, expectedDifference);
        end
    end
end