name: MATLAB Build

on:
  push:
    branches:
      - 'feature/*'    # Only run on feature branches

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      
      # Sets up MATLAB on a GitHub-hosted runner
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025a
          products: >
            MATLAB
            MATLAB_Test

      # Cache .buildtool and test results
      - name: Cache buildtool artifacts
        id: buildtool-cache
        uses: actions/cache@v4
        with:
            path: |
                .buildtool
                results
            key: ${{ runner.os }}-buildtool-cache-${{ github.ref_name }}

      # Run MATLAB build
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: test(RunOnlyImpactedTests=1)
          build-options: -verbosity 3